export type { Abs } from './abs.js'
// export type { Digit, DigitArray } from './Digit.js'
export type { GreaterThan } from './greater_than.js'
export type { Max } from './max.js'
export type { Add, Increment } from './add.js'
export type { Multiply } from './multiply.js'
export type { Decrement, Subtract } from './subtract.js'
