ignores:
  - "@commitlint/*"
  - "@repobuddy/jest"
  - "@semantic-release/*"
  - "@size-limit/preset-small-lib"
  - "@types/node"
  - "@types/jest"
  - babel-jest
  - jest-*
  - semantic-release
  - ts-jest
  - tslib
  - typedoc
  - typedoc-plugin-extras
