version: 2
workflows:
  version: 2
  all:
    jobs:
      - node-latest
      - node11:
          requires:
            - node-latest
      - node10:
          requires:
            - node-latest
      - release:
          filters:
            branches:
              only: master
          requires:
            - node-latest
            - node11
            - node10
jobs:
  node-latest:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          key: node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            if [ ! -d node_modules ]; then
              yarn
            fi
      - save_cache:
          name: Save node modules cache
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: yarn build
      - run: yarn dc
      - persist_to_workspace:
          root: '.'
          paths:
            - lib
            - libm
            - node_modules
      - run: npx size-limit
      - run: yarn coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
      # - run: yarn codecov
  node11:
    docker:
      - image: 'circleci/node:11'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  node10:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  node8:
    docker:
      - image: 'circleci/node:8'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn semantic-release
