ignores:
  - '@commitlint/*'
  - '@jest/globals'
  - '@repobuddy/jest'
  - '@semantic-release/*'
  - '@size-limit/esbuild-why'
  - '@size-limit/preset-small-lib'
  - '@types/node'
  - '@types/jest'
  - '@typescript-eslint/parser'
  - babel-jest
  - jest-*
  - rimraf
  - semantic-release
  - ts-jest
  - tslib
  - typedoc
  - typedoc-plugin-extras
